import 'package:flutter/material.dart';

import '../utilities/green_drawer.dart';
import 'album_card.dart';

class AlbumsPage extends StatelessWidget {
  const AlbumsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Albums"),
      ),
      drawer: const GreenDrawer(),
      body: Center(
        child: GridView.count(
          padding: const EdgeInsets.fromLTRB(0,40,0,0),
          crossAxisCount: 2,
          children: const <Widget>[
            AlbumCard(
              albumTitle: "Blonde on Blonde",
              albumImage: "images/blonde.jpg",
              recordingDate: "1966, 5, 16",
              releaseDate: "1966, 5, 16",
              songs: ["Rainy Day Women #12 & 35",
                "Pledging My Time",
                "Visions of Johanna",
                "One of Us Must Know (Sooner or Later)",
                "I Want You",
                "Stuck Inside of Mobile with the Memphis Blues Again",
                "Leopard-Skin Pill-Box Hat",
                "Just Like a Woman",
                "Most Likely You Go Your Way (and I'll Go Mine)",
                "Temporary Like Achilles",
                "Absolutely Sweet Marie",
                "Fourth Time Around",
                "Obviously Five Believers",
                "Sad-Eyed Lady of the Lowlands"],
              outtakes: ["Can You Please Crawl Out Your Window?",
              "I Wanna Be Your Lover",
                "I'll Keep It with Mine",
                "Jet Pilot",
                "She's Your Lover Now",
               "Lunatic Princess"],
            ),
            AlbumCard(
              albumTitle: "The Freewheelin' Bob Dylan",
              albumImage: "images/freewheelin.jpg",
              recordingDate: "1963, 5, 27",
              releaseDate: "1963, 5, 27",
              songs: [
                "Blowin' in the Wind",
                "Girl from the North Country",
                "Masters of War",
                "Down the Highway",
                "Bob Dylan's Blues",
                "A Hard Rain's A-Gonna Fall",
                "Don't Think Twice, It's All Right",
                "Bob Dylan's Dream",
                "Oxford Town",
                "Talkin' World War III Blues",
                "Corrina, Corrina",
                "Honey, Just Allow Me One More Chance",
                "I Shall Be Free",
              ],
              outtakes: [
                "Going Down To New Orleans",
                "The Death of Emmett Till",
                "Lonesome Whistle Blues",
                "Rambling, Gambling Willie",
                "Worried Blues",
                "Hero Blues",
                "Rocks And Gravel",
                "Talking Bear Mountain Picnic Massacre Blues",
                "Let Me Die in My Footsteps",
                "Talkin' Hava Negeilah Blues",
                "Walls of Red Wing",
                "Quit Your Low Down Ways",
                "Baby, I'm in the Mood for You",
                "Kingsport Town",
                "Whatcha Gonna Do?",
                "Milk Cow Blues",
                "Sally Gal",
                "Baby Please Don't Go",
                "Wichita Blues",
              ],
            ),
            AlbumCard(
              albumTitle: "Highway 61 Revisited",
              albumImage: "images/highway.jpg",
              recordingDate: "1965, 8, 30",
              releaseDate: "1965, 8, 30",
              songs: [
                "Like a Rolling Stone",
                "Tombstone Blues",
                "It Takes a Lot to Laugh, It Takes a Train to Cry",
                "From a Buick 6",
                "Ballad of a Thin Man",
                "Queen Jane Approximately",
                "Highway 61 Revisited",
                "Just Like Tom Thumb's Blues",
                "Desolation Row",
              ],
              outtakes: [
                "Positively 4th Street",
                "Sittin' on a Barbed-Wire Fence",
                "Can You Please Crawl Out Your Window?",
              ],
            ),
            AlbumCard(
              albumTitle: "Bringing It All Back Home",
              albumImage: "images/bringing.jpg",
              recordingDate: "1965, 3, 22",
              releaseDate: "1965, 3, 22",
              songs: [
            "Subterranean Homesick Blues",
            "She Belongs to Me",
            "Maggie's Farm",
            "Love Minus Zero/No Limit",
            "Outlaw Blues",
            "On the Road Again",
            "Bob Dylan's 115th Dream",
            "Mr. Tambourine Man",
            "Gates of Eden",
            "It's Alright, Ma (I'm Only Bleeding)",
            "It's All Over Now, Baby Blue",
              ],
              outtakes: [
                "Farewell Angelina",
                "I'll Keep It with Mine",
                "If You Gotta Go, Go Now",
                "You Don't Have To Do That",
                "California",
              ],
            ),

            AlbumCard(
              albumTitle: "Blonde on Blonde",
              albumImage: "images/blonde.jpg",
              recordingDate: "1966, 5, 16",
              releaseDate: "1966, 5, 16",
              songs: ["Rainy Day Women #12 & 35",
                "Pledging My Time",
                "Visions of Johanna",
                "One of Us Must Know (Sooner or Later)",
                "I Want You",
                "Stuck Inside of Mobile with the Memphis Blues Again",
                "Leopard-Skin Pill-Box Hat",
                "Just Like a Woman",
                "Most Likely You Go Your Way (and I'll Go Mine)",
                "Temporary Like Achilles",
                "Absolutely Sweet Marie",
                "Fourth Time Around",
                "Obviously Five Believers",
                "Sad-Eyed Lady of the Lowlands"],
              outtakes: ["Can You Please Crawl Out Your Window?",
                "I Wanna Be Your Lover",
                "I'll Keep It with Mine",
                "Jet Pilot",
                "She's Your Lover Now",
                "Lunatic Princess"],
            ),
            AlbumCard(
              albumTitle: "The Freewheelin' Bob Dylan",
              albumImage: "images/freewheelin.jpg",
              recordingDate: "1963, 5, 27",
              releaseDate: "1963, 5, 27",
              songs: [
                "Blowin' in the Wind",
                "Girl from the North Country",
                "Masters of War",
                "Down the Highway",
                "Bob Dylan's Blues",
                "A Hard Rain's A-Gonna Fall",
                "Don't Think Twice, It's All Right",
                "Bob Dylan's Dream",
                "Oxford Town",
                "Talkin' World War III Blues",
                "Corrina, Corrina",
                "Honey, Just Allow Me One More Chance",
                "I Shall Be Free",
              ],
              outtakes: [
                "Going Down To New Orleans",
                "The Death of Emmett Till",
                "Lonesome Whistle Blues",
                "Rambling, Gambling Willie",
                "Worried Blues",
                "Hero Blues",
                "Rocks And Gravel",
                "Talking Bear Mountain Picnic Massacre Blues",
                "Let Me Die in My Footsteps",
                "Talkin' Hava Negeilah Blues",
                "Walls of Red Wing",
                "Quit Your Low Down Ways",
                "Baby, I'm in the Mood for You",
                "Kingsport Town",
                "Whatcha Gonna Do?",
                "Milk Cow Blues",
                "Sally Gal",
                "Baby Please Don't Go",
                "Wichita Blues",
              ],
            ),
            AlbumCard(
              albumTitle: "Highway 61 Revisited",
              albumImage: "images/highway.jpg",
              recordingDate: "1965, 8, 30",
              releaseDate: "1965, 8, 30",
              songs: [
                "Like a Rolling Stone",
                "Tombstone Blues",
                "It Takes a Lot to Laugh, It Takes a Train to Cry",
                "From a Buick 6",
                "Ballad of a Thin Man",
                "Queen Jane Approximately",
                "Highway 61 Revisited",
                "Just Like Tom Thumb's Blues",
                "Desolation Row",
              ],
              outtakes: [
                "Positively 4th Street",
                "Sittin' on a Barbed-Wire Fence",
                "Can You Please Crawl Out Your Window?",
              ],
            ),
            AlbumCard(
              albumTitle: "Bringing It All Back Home",
              albumImage: "images/bringing.jpg",
              recordingDate: "1965, 3, 22",
              releaseDate: "1965, 3, 22",
              songs: [
                "Subterranean Homesick Blues",
                "She Belongs to Me",
                "Maggie's Farm",
                "Love Minus Zero/No Limit",
                "Outlaw Blues",
                "On the Road Again",
                "Bob Dylan's 115th Dream",
                "Mr. Tambourine Man",
                "Gates of Eden",
                "It's Alright, Ma (I'm Only Bleeding)",
                "It's All Over Now, Baby Blue",
              ],
              outtakes: [
                "Farewell Angelina",
                "I'll Keep It with Mine",
                "If You Gotta Go, Go Now",
                "You Don't Have To Do That",
                "California",
              ],
            ),

            AlbumCard(
              albumTitle: "Blonde on Blonde",
              albumImage: "images/blonde.jpg",
              recordingDate: "1966, 5, 16",
              releaseDate: "1966, 5, 16",
              songs: ["Rainy Day Women #12 & 35",
                "Pledging My Time",
                "Visions of Johanna",
                "One of Us Must Know (Sooner or Later)",
                "I Want You",
                "Stuck Inside of Mobile with the Memphis Blues Again",
                "Leopard-Skin Pill-Box Hat",
                "Just Like a Woman",
                "Most Likely You Go Your Way (and I'll Go Mine)",
                "Temporary Like Achilles",
                "Absolutely Sweet Marie",
                "Fourth Time Around",
                "Obviously Five Believers",
                "Sad-Eyed Lady of the Lowlands"],
              outtakes: ["Can You Please Crawl Out Your Window?",
                "I Wanna Be Your Lover",
                "I'll Keep It with Mine",
                "Jet Pilot",
                "She's Your Lover Now",
                "Lunatic Princess"],
            ),
            AlbumCard(
              albumTitle: "The Freewheelin' Bob Dylan",
              albumImage: "images/freewheelin.jpg",
              recordingDate: "1963, 5, 27",
              releaseDate: "1963, 5, 27",
              songs: [
                "Blowin' in the Wind",
                "Girl from the North Country",
                "Masters of War",
                "Down the Highway",
                "Bob Dylan's Blues",
                "A Hard Rain's A-Gonna Fall",
                "Don't Think Twice, It's All Right",
                "Bob Dylan's Dream",
                "Oxford Town",
                "Talkin' World War III Blues",
                "Corrina, Corrina",
                "Honey, Just Allow Me One More Chance",
                "I Shall Be Free",
              ],
              outtakes: [
                "Going Down To New Orleans",
                "The Death of Emmett Till",
                "Lonesome Whistle Blues",
                "Rambling, Gambling Willie",
                "Worried Blues",
                "Hero Blues",
                "Rocks And Gravel",
                "Talking Bear Mountain Picnic Massacre Blues",
                "Let Me Die in My Footsteps",
                "Talkin' Hava Negeilah Blues",
                "Walls of Red Wing",
                "Quit Your Low Down Ways",
                "Baby, I'm in the Mood for You",
                "Kingsport Town",
                "Whatcha Gonna Do?",
                "Milk Cow Blues",
                "Sally Gal",
                "Baby Please Don't Go",
                "Wichita Blues",
              ],
            ),
            AlbumCard(
              albumTitle: "Highway 61 Revisited",
              albumImage: "images/highway.jpg",
              recordingDate: "1965, 8, 30",
              releaseDate: "1965, 8, 30",
              songs: [
                "Like a Rolling Stone",
                "Tombstone Blues",
                "It Takes a Lot to Laugh, It Takes a Train to Cry",
                "From a Buick 6",
                "Ballad of a Thin Man",
                "Queen Jane Approximately",
                "Highway 61 Revisited",
                "Just Like Tom Thumb's Blues",
                "Desolation Row",
              ],
              outtakes: [
                "Positively 4th Street",
                "Sittin' on a Barbed-Wire Fence",
                "Can You Please Crawl Out Your Window?",
              ],
            ),
            AlbumCard(
              albumTitle: "Bringing It All Back Home",
              albumImage: "images/bringing.jpg",
              recordingDate: "1965, 3, 22",
              releaseDate: "1965, 3, 22",
              songs: [
                "Subterranean Homesick Blues",
                "She Belongs to Me",
                "Maggie's Farm",
                "Love Minus Zero/No Limit",
                "Outlaw Blues",
                "On the Road Again",
                "Bob Dylan's 115th Dream",
                "Mr. Tambourine Man",
                "Gates of Eden",
                "It's Alright, Ma (I'm Only Bleeding)",
                "It's All Over Now, Baby Blue",
              ],
              outtakes: [
                "Farewell Angelina",
                "I'll Keep It with Mine",
                "If You Gotta Go, Go Now",
                "You Don't Have To Do That",
                "California",
              ],
            ),
          ],
        ),
      ),
    );
  }
}
